name = "registry"
main = "src/index.js"
compatibility_date = "2023-12-01"

[route]
pattern = "registry.moonrhythm.io"
custom_domain = true

[vars]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "registry"

[[d1_databases]]
binding = "DB"
database_id = "e1233b26-0da3-4c43-a60d-09d6f7c7ee0c"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "registry"
